# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resnet_model_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='resnet_model_config.proto',
  package='resnet.configs',
  serialized_pb=_b('\n\x19resnet_model_config.proto\x12\x0eresnet.configs\"\xa1\x05\n\x11ResnetModelConfig\x12\x14\n\x0cinput_height\x18\x01 \x01(\x05\x12\x13\n\x0binput_width\x18\x02 \x01(\x05\x12\x17\n\x0cnum_channels\x18\x03 \x01(\x05:\x01\x33\x12\x13\n\x0bnum_classes\x18\x04 \x01(\x05\x12\x1a\n\x12num_residual_units\x18\x05 \x03(\x05\x12\x13\n\x0bnum_filters\x18\x06 \x03(\x05\x12\x0f\n\x07strides\x18\x07 \x03(\x05\x12\x11\n\tdilations\x18\x08 \x03(\x05\x12\x13\n\x0binit_stride\x18\t \x01(\x05\x12\x15\n\rinit_max_pool\x18\n \x01(\x08\x12\x18\n\x10init_filter_size\x18\x0b \x01(\x05\x12\x16\n\x0euse_bottleneck\x18\x0c \x01(\x08\x12\x18\n\x10\x62uild_classifier\x18\r \x01(\x08\x12\x14\n\x0cweight_decay\x18\x0e \x01(\x02\x12\x19\n\x0b\x64\x61ta_format\x18\x0f \x01(\t:\x04NHWC\x12\x12\n\x07\x64ropout\x18\x10 \x01(\x02:\x01\x30\x12!\n\x0eoptimizer_type\x18\xe9\x07 \x01(\t:\x08momentum\x12\x13\n\nlearn_rate\x18\xea\x07 \x01(\x02\x12\x11\n\x08momentum\x18\xeb\x07 \x01(\x02\x12\x19\n\x10train_batch_size\x18\xec\x07 \x01(\x05\x12\x18\n\x0f\x65val_batch_size\x18\xed\x07 \x01(\x05\x12\x17\n\x0emax_train_iter\x18\xee\x07 \x01(\x05\x12\x1f\n\x16learn_rate_decay_steps\x18\xef\x07 \x03(\x05\x12\"\n\x19learn_rate_scheduler_type\x18\xf0\x07 \x03(\t\x12\x18\n\x0flearn_rate_list\x18\xf1\x07 \x03(\x02\x12\x13\n\x04seed\x18\xf2\x07 \x01(\x05:\x04\x31\x32\x33\x34\x12\x14\n\x07version\x18\xd0\x0f \x01(\t:\x02v1')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESNETMODELCONFIG = _descriptor.Descriptor(
  name='ResnetModelConfig',
  full_name='resnet.configs.ResnetModelConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_height', full_name='resnet.configs.ResnetModelConfig.input_height', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_width', full_name='resnet.configs.ResnetModelConfig.input_width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_channels', full_name='resnet.configs.ResnetModelConfig.num_channels', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_classes', full_name='resnet.configs.ResnetModelConfig.num_classes', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_residual_units', full_name='resnet.configs.ResnetModelConfig.num_residual_units', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_filters', full_name='resnet.configs.ResnetModelConfig.num_filters', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strides', full_name='resnet.configs.ResnetModelConfig.strides', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dilations', full_name='resnet.configs.ResnetModelConfig.dilations', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='init_stride', full_name='resnet.configs.ResnetModelConfig.init_stride', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='init_max_pool', full_name='resnet.configs.ResnetModelConfig.init_max_pool', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='init_filter_size', full_name='resnet.configs.ResnetModelConfig.init_filter_size', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_bottleneck', full_name='resnet.configs.ResnetModelConfig.use_bottleneck', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='build_classifier', full_name='resnet.configs.ResnetModelConfig.build_classifier', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight_decay', full_name='resnet.configs.ResnetModelConfig.weight_decay', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_format', full_name='resnet.configs.ResnetModelConfig.data_format', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("NHWC").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dropout', full_name='resnet.configs.ResnetModelConfig.dropout', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='optimizer_type', full_name='resnet.configs.ResnetModelConfig.optimizer_type', index=16,
      number=1001, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("momentum").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learn_rate', full_name='resnet.configs.ResnetModelConfig.learn_rate', index=17,
      number=1002, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='momentum', full_name='resnet.configs.ResnetModelConfig.momentum', index=18,
      number=1003, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_batch_size', full_name='resnet.configs.ResnetModelConfig.train_batch_size', index=19,
      number=1004, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_batch_size', full_name='resnet.configs.ResnetModelConfig.eval_batch_size', index=20,
      number=1005, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_train_iter', full_name='resnet.configs.ResnetModelConfig.max_train_iter', index=21,
      number=1006, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learn_rate_decay_steps', full_name='resnet.configs.ResnetModelConfig.learn_rate_decay_steps', index=22,
      number=1007, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learn_rate_scheduler_type', full_name='resnet.configs.ResnetModelConfig.learn_rate_scheduler_type', index=23,
      number=1008, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learn_rate_list', full_name='resnet.configs.ResnetModelConfig.learn_rate_list', index=24,
      number=1009, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seed', full_name='resnet.configs.ResnetModelConfig.seed', index=25,
      number=1010, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1234,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='resnet.configs.ResnetModelConfig.version', index=26,
      number=2000, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("v1").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=719,
)

DESCRIPTOR.message_types_by_name['ResnetModelConfig'] = _RESNETMODELCONFIG

ResnetModelConfig = _reflection.GeneratedProtocolMessageType('ResnetModelConfig', (_message.Message,), dict(
  DESCRIPTOR = _RESNETMODELCONFIG,
  __module__ = 'resnet_model_config_pb2'
  # @@protoc_insertion_point(class_scope:resnet.configs.ResnetModelConfig)
  ))
_sym_db.RegisterMessage(ResnetModelConfig)


# @@protoc_insertion_point(module_scope)
